name: Bug report
description: Report a reproducible bug in ScaleDown
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: input
    id: version
    attributes:
      label: ScaleDown version
      placeholder: e.g. 0.1.0
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: e.g. 3.11.9
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Affected component
      options:
        - Compressor
        - HASTE optimizer
        - Semantic optimizer
        - Pipeline
        - Packaging / Installation
        - Other
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide a minimal reproducible example.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs / tracebacks
      render: shell
